Repository swiftlang/swift-sdk-generator, pull requests merged in 2023-09, with the labels that each got.

#8 Add missing closing bracket in option help
  Sources/GeneratorCLI/GeneratorCLI.swift
Labels: documentation

#13 Make CPU architecture options shorter
  Sources/GeneratorCLI/GeneratorCLI.swift
Labels: enhancement

#14 Update to the latest tag of AsyncAlgorithms
  Package.resolved
  Package.swift
Labels: dependencies

#16 Allow downloading LLVM project source for building `lld`
  Sources/SwiftSDKGenerator/Artifacts/DownloadableArtifacts.swift
  Sources/SwiftSDKGenerator/Generator/LocalSwiftSDKGenerator.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
Labels: enhancement

#18 Add `case wasi` and `case win32` to the `Triple.OS` enum
  Sources/SwiftSDKGenerator/Artifacts/DownloadableArtifacts.swift
  Sources/SwiftSDKGenerator/PlatformModels/Triple.swift
Labels: enhancement

#19 Build `lld` when no prebuilt binaries are available
  Sources/SwiftSDKGenerator/Artifacts/DownloadableArtifacts.swift
  Sources/SwiftSDKGenerator/Generator/LocalSwiftSDKGenerator.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Build.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
  Sources/SwiftSDKGenerator/PlatformModels/Triple.swift
Labels: bug

#21 Clarify x86_64 support in `README.md`
  README.md
Labels: documentation
