Repository swiftlang/swift-sdk-generator, pull requests merged in 2023-11, with the labels that each got.

#36 Fix cross-compilation with static linking when using C interop
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Fixup.swift
Labels: bug

#37 Remove unused Darwin platforms from the host toolchain
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
Labels: enhancement

#31 Add `GeneratorEngine` module with tests and macros
  Docker/Dockerfile
  Package.resolved
  Package.swift
  Sources/GeneratorEngine/Cache/CacheKeyProtocol.swift
  Sources/GeneratorEngine/Cache/FileCacheRecord.swift
  Sources/GeneratorEngine/Cache/SQLite.swift
  Sources/GeneratorEngine/Cache/SQLiteBackedCache.swift
  Sources/GeneratorEngine/Engine.swift
  Sources/GeneratorEngine/FileSystem/FileLock.swift
  Sources/GeneratorEngine/FileSystem/FileSystem.swift
  Sources/GeneratorEngine/FileSystem/LocalFileSystem.swift
  Sources/GeneratorEngine/FileSystem/OpenReadableFile.swift
  Sources/GeneratorEngine/FileSystem/OpenWritableFile.swift
  Sources/GeneratorEngine/FileSystem/ReadableFileStream.swift
  Sources/GeneratorEngine/FileSystem/VirtualFileSystem.swift
  Sources/GeneratorEngine/Query.swift
  Sources/Macros/CacheKeyMacro.swift
  Sources/Macros/Macros.swift
  Sources/Macros/QueryMacro.swift
  Sources/Macros/SimpleDiagnosticMessage.swift
  Tests/GeneratorEngineTests/EngineTests.swift
  Tests/MacrosTests/MacrosTests.swift
Labels: enhancement

#35 Cache `lld` binaries to avoid redundant rebuilds
  Sources/GeneratorEngine/Cache/CacheKeyProtocol.swift
  Sources/GeneratorEngine/Cache/FileCacheRecord.swift
  Sources/GeneratorEngine/Cache/SQLite.swift
  Sources/SwiftSDKGenerator/Artifacts/DownloadableArtifacts.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Build.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
  Sources/SwiftSDKGenerator/Queries/CMakeBuildQuery.swift
  Sources/SwiftSDKGenerator/Queries/DownloadArtifactQuery.swift
Labels: enhancement

#38 Cache downloads of `.deb` packages w/ `DownloadFileQuery`
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
  Sources/SwiftSDKGenerator/Queries/DownloadFileQuery.swift
  Sources/SwiftSDKGenerator/SystemUtils/HTTPClient+Download.swift
Labels: enhancement

#43 docker: Support generating an SDK from a custom container image
  README.md
  Sources/GeneratorCLI/GeneratorCLI.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
Labels: enhancement

#44 Update `swift-async-algorithms` to 1.0.0-beta.1
  Package.resolved
  Package.swift
  Sources/SwiftSDKGenerator/Queries/DownloadArtifactQuery.swift
  Utilities/test.sh
Labels: dependencies

#49 Attach relevant `FilePath` values to `Errno` errors
  Sources/AsyncProcess/ProcessExecutor+Convenience.swift
  Sources/GeneratorEngine/FileSystem/FileLock.swift
  Sources/GeneratorEngine/FileSystem/FileSystem.swift
  Sources/GeneratorEngine/FileSystem/LocalFileSystem.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Fixup.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
  Sources/SwiftSDKGenerator/Queries/DownloadFileQuery.swift
Labels: enhancement

#52 generator: Disable all libllvm targets when building lld
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
Labels: performance

#47 Cancel tasks when receiving a `SIGINT` signal
  Package.resolved
  Package.swift
  Sources/GeneratorCLI/GeneratorCLI.swift
  Sources/GeneratorEngine/Engine.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
  Sources/SwiftSDKGenerator/Queries/CMakeBuildQuery.swift
  Sources/SwiftSDKGenerator/SystemUtils/Shell.swift
  Tests/SwiftSDKGeneratorTests/ArchitectureMappingTests.swift
Labels: bug

#53 Use Swift 5.9.1 and LLD 17.0.5 by default
  Sources/GeneratorCLI/GeneratorCLI.swift
Labels: dependencies

#54 Fix `fatalError` failure for development snapshots
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
Labels: bug

#55 Rethrow error in `withEngine`
  Sources/GeneratorEngine/Engine.swift
Labels: bug

#56 Rethrow error from `withHTTPClient`
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
Labels: bug
