Repository swiftlang/swift-sdk-generator, pull requests merged in 2024-08, with the labels that each got.

#123 Update license years in `README.md` (2024)
  README.md
Labels: documentation

#124 Add `.editorconfig` file
  .editorconfig
Labels: no functional change

#125 Fix a compatibility issue with Swift 6.0 and `main` snapshots
  Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
Labels: bug

#128 Bump default version of Swift to 5.10.1
  Sources/GeneratorCLI/GeneratorCLI.swift
Labels: dependencies

#130 Fix `print` copy in `GeneratorCLI.swift`
  Sources/GeneratorCLI/GeneratorCLI.swift
Labels: bug

#131 Add `/.index-build` to `.gitignore`
  .gitignore
Labels: bug

#133 Fix `AsyncProcessTests/testCanDealWithRunawayChildProcesses`
  Tests/AsyncProcessTests/IntegrationTests.swift
Labels: bug, test suite

#134 Check for `LeafCacheKey` in more `HashEncoder` functions
  Sources/GeneratorEngine/Cache/CacheKey.swift
  Sources/GeneratorEngine/Query.swift
  Tests/GeneratorEngineTests/EngineTests.swift
Labels: bug

#135 Use `github.com/swiftlang` instead of `github.com/apple` in `README.md`
  README.md
Labels: documentation

#129 WasmSDK: Copy swift-foundation headers and apinotes into the Swift SDK bundle
  Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
Labels: dependencies

#136 Enable Swift 6 mode when available, sync `QueryEngine` sources
  Package.swift
  Sources/AsyncProcess/ProcessExecutor.swift
  Sources/GeneratorEngine/Cache/FileCacheRecord.swift
  Sources/GeneratorEngine/FileSystem/FileSystem.swift
  Sources/GeneratorEngine/FileSystem/OpenReadableFile.swift
  Sources/GeneratorEngine/FileSystem/OpenWritableFile.swift
  Sources/GeneratorEngine/FileSystem/ReadableFileStream.swift
  Sources/GeneratorEngine/FileSystem/VirtualFileSystem.swift
  Sources/GeneratorEngine/Query.swift
  Sources/Helpers/Vendor/QueryEngine/CacheKey.swift
  Sources/Helpers/Vendor/QueryEngine/FileCacheRecord.swift
  Sources/Helpers/Vendor/QueryEngine/FileLock.swift
  Sources/Helpers/Vendor/QueryEngine/Query.swift
  Sources/Helpers/Vendor/QueryEngine/QueryEngine.swift
  Sources/Helpers/Vendor/QueryEngine/SQLite.swift
  Sources/Helpers/Vendor/QueryEngine/SQLiteBackedCache.swift
  Sources/Helpers/Vendor/README.md
  Sources/Helpers/Vendor/Triple.swift
  Sources/Helpers/Vendor/_AsyncFileSystem/AsyncFileSystem.swift
  Sources/Helpers/Vendor/_AsyncFileSystem/ConcurrencySupport.swift
  Sources/Helpers/Vendor/_AsyncFileSystem/MockFileSystem.swift
  Sources/Helpers/Vendor/_AsyncFileSystem/OSFileSystem.swift
  Sources/Helpers/Vendor/_AsyncFileSystem/OpenReadableFile.swift
  Sources/Helpers/Vendor/_AsyncFileSystem/OpenWritableFile.swift
  Sources/Helpers/Vendor/_AsyncFileSystem/ReadableFileStream.swift
  Sources/Helpers/Vendor/_AsyncFileSystem/WritableStream.swift
  Sources/SwiftSDKGenerator/Artifacts/DownloadableArtifacts.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
  Sources/SwiftSDKGenerator/Queries/CMakeBuildQuery.swift
  Sources/SwiftSDKGenerator/Queries/DownloadArtifactQuery.swift
  Sources/SwiftSDKGenerator/Queries/DownloadFileQuery.swift
  Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
  Sources/SwiftSDKGenerator/SwiftSDKRecipes/SwiftSDKRecipe.swift
  Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
  Tests/AsyncProcessTests/IntegrationTests.swift
  Tests/GeneratorEngineTests/EngineTests.swift
  Tests/SwiftSDKGeneratorTests/EndToEndTests.swift
Labels: dependencies
