Repository swiftlang/swift-sdk-generator, pull requests merged in 2024-02, with the labels that each got.

#82 Keep Swift libraries linked by compiler tools
  Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
Labels: bug

#83 generator: Don't build other `llvm` binaries when building `lld` from source
  Sources/SwiftSDKGenerator/Queries/CMakeBuildQuery.swift
Labels: performance

#84 WebAssembly: Make `--host-swift-package-path` optional for WebAssembly recipe
  Sources/GeneratorCLI/GeneratorCLI.swift
  Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
Labels: enhancement

#85 WebAssembly: Specify resource directory explicitly
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Metadata.swift
  Sources/SwiftSDKGenerator/Serialization/SwiftSDKMetadata.swift
  Sources/SwiftSDKGenerator/SwiftSDKRecipes/SwiftSDKRecipe.swift
  Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
Labels: bug
