Repository swiftlang/swift-sdk-generator, pull requests merged in 2025-04, with the labels that each got.

#205 Update `.swift-format` rules
  .swift-format
  Sources/AsyncProcess/FileContentStream.swift
  Sources/AsyncProcess/ProcessExecutor+Convenience.swift
  Sources/AsyncProcess/ProcessExecutor.swift
  Sources/GeneratorCLI/GeneratorCLI.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Fixup.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Metadata.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
  Sources/SwiftSDKGenerator/PlatformModels/LinuxDistribution.swift
  Sources/SwiftSDKGenerator/Queries/DownloadArtifactQuery.swift
  Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
  Sources/SwiftSDKGenerator/SwiftSDKRecipes/SwiftSDKRecipe.swift
  Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
  Sources/SwiftSDKGenerator/SystemUtils/ByteBuffer+Utils.swift
  Sources/SwiftSDKGenerator/SystemUtils/HTTPClient+Download.swift
  Sources/SwiftSDKGenerator/SystemUtils/which.swift
  Tests/AsyncProcessTests/AsyncByteBufferLineSequenceTests.swift
  Tests/AsyncProcessTests/IntegrationTests.swift
  Tests/GeneratorEngineTests/EngineTests.swift
  Tests/SwiftSDKGeneratorTests/EndToEndTests.swift
  Tests/SwiftSDKGeneratorTests/SwiftSDKRecipes/LinuxRecipeTests.swift
  Tests/SwiftSDKGeneratorTests/SwiftSDKRecipes/WebAssemblyRecipe.swift
Labels: no functional change

#204 Update defaults for Swift 6.1-RELEASE
  Sources/GeneratorCLI/GeneratorCLI.swift
  Sources/SwiftSDKGenerator/Artifacts/DownloadableArtifacts.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
  Sources/SwiftSDKGenerator/PlatformModels/VersionsConfiguration.swift
  Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
  Tests/SwiftSDKGeneratorTests/EndToEndTests.swift
Labels: dependencies

#206 docs: Delete instructions to run non-existent soundness.sh
  CONTRIBUTING.md
Labels: documentation, no functional change

#203 Support Debian 11 and Debian 12 distributions in the generator
  README.md
  Sources/GeneratorCLI/GeneratorCLI.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
  Sources/SwiftSDKGenerator/PlatformModels/LinuxDistribution.swift
  Sources/SwiftSDKGenerator/PlatformModels/VersionsConfiguration.swift
  Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
  Sources/SwiftSDKGenerator/SystemUtils/ByteBuffer+Utils.swift
  Sources/SwiftSDKGenerator/SystemUtils/GeneratorError.swift
  Tests/SwiftSDKGeneratorTests/EndToEndTests.swift
  Tests/SwiftSDKGeneratorTests/SwiftSDKRecipes/LinuxRecipeTests.swift
Labels: enhancement
