Repository swiftlang/swift-sdk-generator, pull requests merged in 2025-01, with the labels that each got.

#165 Add new options that control whether host toolchain is included
  Sources/GeneratorCLI/GeneratorCLI.swift
  Sources/Helpers/Vendor/Triple.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
  Sources/SwiftSDKGenerator/Serialization/Toolset.swift
  Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
  Tests/SwiftSDKGeneratorTests/SwiftSDKRecipes/LinuxRecipeTests.swift
Labels: enhancement

#171 generator: Sort keys in JSON metadata files
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Metadata.swift
Labels: test suite, no functional change

#169 generator: Use Swift 6.0.3 by default
  Sources/GeneratorCLI/GeneratorCLI.swift
  Tests/SwiftSDKGeneratorTests/EndToEndTests.swift
Labels: enhancement

#172 generator: Add an environment variable to choose the container runtime
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
  Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
Labels: enhancement

#173 generator: Do not include the host toolchain by default
  Sources/GeneratorCLI/GeneratorCLI.swift
Labels: enhancement

#174 generator: --from-container-image implies --with-docker
  README.md
  Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
Labels: enhancement

#175 tests: End to end tests still require host toolchains
  Tests/SwiftSDKGeneratorTests/EndToEndTests.swift
Labels: test suite

#177 generator: Do not attempt to download toolchain if it is not needed
  Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
Labels: enhancement, performance
